plugins:
- jekyll-paginate

# karmdown config
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]

# Permalinks
permalink:        pretty

# Setup
title:            l33tsource
tagline:          '$dinge'
description:      'Sometimes random blog posts appear.'
url:              https://l33tsource.com

author:
  name: Sir l33tname
  email: hi@l33t.name

paginate:         5
